### ISSUE TITLE
Writing to file

### ISSUE THREAD

**Issue by utamons** [Miraschon/hello-world#1]
Create a list with 3 strings, write the list to a file

**Comment by Miraschon** [comment]
package com.mycompany.app;

import java.io.IOException;
import java.util.ArrayList;
import java.io.FileWriter;

/**
 * Hello world!
 *
 */
public class App 
{
    public App() throws IOException {
    }

    public static void main(String[] args ) throws IOException {
        ArrayList<String> strings = new ArrayList<String>();
        strings.add("string1");
        strings.add("string2");
        strings.add("string3");
        FileWriter writer = new FileWriter("output.txt");
        for(String str: strings) {
            writer.write(str);
        }
        writer.close();
    }

}
